CPP = g++
CFLAGS = -Wall -ansi -g

solution13: solution13.o ../../Integer/Integer.o 
	$(CPP) $(CFLAGS) -o solution13 solution13.o ../../Integer/Integer.o

solution13.o: solution13.cc 
	$(CPP) $(CFLAGS) -c solution13.cc
